parameters:
#    crystal_base.example.class: Crystal\BaseBundle\Example

services:
#    crystal_base.example:
#        class: %crystal_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
