<?php

namespace Crystal\RumbaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MultimediaController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Crystal\RumbaBundle\Controller\MultimediaController();
        return $instance;
    }
}
